# STAT5342 Project 1 
**By Yiming Zhu yz4336**

# Introduction of dataset
For this project, I use the History of Philosophy dataset. This data site is about the sentences given by different philosophers from different schools. In this dataset, we can exam the pattern, the word choice of differet philosopher. 

Source: https://www.kaggle.com/datasets/kouroshalizadeh/history-of-philosophy?resource=download

#Question1: Among *analytic* and *aristotle*, philosophers from which school prefer long sentences

I wonder if the different teaching methods in different schools will affect the language models of philosophers. For example, some colleges choose textbooks, so philosophers in that college tend to choose longer philosophical sentences. To investigate this question, I choose two schools that I am interested most, analytic and aristotle. 

#Method
To investigate this question, I choose two schools that I am interested most, analytic and aristotle. Firstly, I wrangle the data so that it has two column: *school* and *sentence_length*. Here, school only contains records of analytic and aristotle. 

Then I calculted *Pearson's chi-squared test* of the sentence length across schools to explore whether there were significant differences. Pearson's chi-squared test is a statistical test used to determine if there is a significant difference between the observed and expected frequencies in one or more categorical variables. It is commonly used to determine if there is a relationship between two categorical variables. The test calculates the chi-squared statistic, which is a measure of the difference between the observed and expected frequencies, and compares it to a critical value from the chi-squared distribution to determine if the difference is significant. The result of the test can be used to accept or reject the null hypothesis that the variables are independent.

In [2]:
from google.colab import drive
drive.mount('/content/drive') 
import pandas as pd

philosophy=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/STAT5243/philosophy_data.csv')

Mounted at /content/drive

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/STAT5243/philosophy_data.csv')
df.head(10)

,title,author,school,sentence_spacy,sentence_str,original_publication_date,corpus_edition_date,sentence_length,sentence_lowered,tokenized_txt,lemmatized_str
0,Plato - Complete Works,Plato,plato,"What's new, Socrates, to make you leave your ...","What's new, Socrates, to make you leave your ...",-350,1997,125,"what's new, socrates, to make you leave your ...","['what', 'new', 'socrates', 'to', 'make', 'you...","what be new , Socrates , to make -PRON- lea..."
1,Plato - Complete Works,Plato,plato,Surely you are not prosecuting anyone before t...,Surely you are not prosecuting anyone before t...,-350,1997,69,surely you are not prosecuting anyone before t...,"['surely', 'you', 'are', 'not', 'prosecuting',...",surely -PRON- be not prosecute anyone before ...
2,Plato - Complete Works,Plato,plato,The Athenians do not call this a prosecution b...,The Athenians do not call this a prosecution b...,-350,1997,74,the athenians do not call this a prosecution b...,"['the', 'athenians', 'do', 'not', 'call', 'thi...",the Athenians do not call this a prosecution ...
3,Plato - Complete Works,Plato,plato,What is this you say?,What is this you say?,-350,1997,21,what is this you say?,"['what', 'is', 'this', 'you', 'say']",what be this -PRON- say ?
4,Plato - Complete Works,Plato,plato,"Someone must have indicted you, for you are no...","Someone must have indicted you, for you are no...",-350,1997,101,"someone must have indicted you, for you are no...","['someone', 'must', 'have', 'indicted', 'you',...","someone must have indict -PRON- , for -PRON- ..."
5,Plato - Complete Works,Plato,plato,But someone else has indicted you?,But someone else has indicted you?,-350,1997,34,but someone else has indicted you?,"['but', 'someone', 'else', 'has', 'indicted', ...",but someone else have indict -PRON- ?
6,Plato - Complete Works,Plato,plato,"I do not really know him myself, Euthyphro.","I do not really know him myself, Euthyphro.",-350,1997,43,"i do not really know him myself, euthyphro.","['do', 'not', 'really', 'know', 'him', 'myself...","-PRON- do not really know -PRON- -PRON- , Eut..."
7,Plato - Complete Works,Plato,plato,He is apparently young and unknown.,He is apparently young and unknown.,-350,1997,35,he is apparently young and unknown.,"['he', 'is', 'apparently', 'young', 'and', 'un...",-PRON- be apparently young and unknown .
8,Plato - Complete Works,Plato,plato,"They call him Meletus, I believe.","They call him Meletus, I believe.",-350,1997,33,"they call him meletus, i believe.","['they', 'call', 'him', 'meletus', 'believe']","-PRON- call -PRON- Meletus , -PRON- believe ."
9,Plato - Complete Works,Plato,plato,"He belongs to the Pitthean deme, if you know a...","He belongs to the Pitthean deme, if you know a...",-350,1997,147,"he belongs to the pitthean deme, if you know a...","['he', 'belongs', 'to', 'the', 'pitthean', 'de...","-PRON- belong to the Pitthean deme , if -PRON..."

In [4]:
df2=df[df['school'].isin(['analytic','aristotle'])].reset_index() 
df3=df2[['school','sentence_length']]

In [5]:
from scipy.stats import chisquare
chisquare(df3['school'].value_counts())

Power_divergenceResult(statistic=423.8735173313884, pvalue=3.5021803536319334e-94)

In our analysis, the p-value of the chi-squared test is less than 0.05. Hence, there is no difference of the sentence length between *analytic* and *aristotle*.

#Question2: Which philosopher's sentence has the longest average sentence length

I'm curious whether different philosophers have significant differences in the length of sentences. 

#Method
To explore this question, I group the data by the author and calculate the average sentence length for each philosopher and compared them.

In [12]:
df5 = df.groupby('author')['sentence_length'].aggregate(['mean'])
df5

                       mean
author
Aristotle        153.224953
Beauvoir         148.790351
Berkeley         139.653987
Davis            139.671134
Deleuze          163.671850
Derrida          143.431239
Descartes        247.381625
Epictetus        118.430341
Fichte           151.964582
Foucault         189.637467
Hegel            175.720088
Heidegger        118.541965
Hume             180.192372
Husserl          185.473703
Kant             198.159400
Keynes           196.654060
Kripke           119.025082
Leibniz          157.085140
Lenin            181.423137
Lewis            109.717607
Locke            200.395836
Malebranche      164.434023
Marcus Aurelius  139.776221
Marx             143.253466
Merleau-Ponty    170.934009
Moore            167.254907
Nietzsche        116.599867
Plato            114.938018
Popper           139.545105
Quine            121.643429
Ricardo          186.252751
Russell          146.296669
Smith            185.277944
Spinoza          146.544424
Wittgenstein      84.883772
Wollstonecraft   190.957796

Based on the DataFrame above, we can see that different authors have different avgerage sentence length. Wittgenstein has average sentence length of 84.883772 words, while Descartes	has average sentence length of 247.381625. So different authors have very different avgerage sentence length.